---
weight_dir: /home/kacper/data/EPE/weights # path to folder where checkpoints should be stored

common:
  unpin: false # disable pinning for the loader
  batch_size: 1
  num_loaders: 6
  log_interval: 50 # print losses evey X iterations
  seed: 1

train:
  max_epochs: -1
  max_iterations: 1000000
  save_epochs: -1 # save every X epochs
  save_iterations: 10000 # save every X iterations
  shuffle_train: true
  val_interval: 750 # run inference on validation set every X iterations
  no_validation: False

test:
  shuffle_test: false

real_dataset:
  name: real
  filelist: /home/kacper/code/EPE/datasets/somers_town/real_files.csv # file with run_id and timestamp pairs
  data_root: '/home/kacper/data/datasets'

fake_dataset:
  name: sim

  g_buffers: ["depth", "normal"]
  gbuf_stats_path: /home/kacper/code/EPE/datasets/somers_town/gbuf_stats.pt # file with run_id and timestamp pairs

  train_filelist: /home/kacper/code/EPE/datasets/somers_town/sim_files.csv # file with run_id and timestamp pairs
  val_filelist: /home/kacper/code/EPE/datasets/somers_town/sim_files.csv # file with run_id and timestamp pairs
  test_filelist: /home/kacper/code/EPE/datasets/somers_town/sim_files.csv # file with run_id and timestamp pairs


  data_root: '/home/kacper/data/datasets'

  sampling: 
    type: 'matching'
    matched_crop_path: /home/kacper/code/EPE/datasets/somers_town/matched_crops_sim-real.csv # generated by matching/filter.py
    crop_weight_path: /home/kacper/code/EPE/datasets/somers_town/crop_weights_sim-real.npz # generated by matching/compute_weights.py

generator:
  type: hr_new
  config:
    encoder_type: ENCODER
    stem_norm: group
    num_stages: 5
    other_norm: group
    gbuffer_norm: RAC
    gbuffer_encoder_norm: residual2
    num_gbuffer_layers: 3
  optimizer:
    type: adam
    learning_rate: 0.0001
    adam_beta: 0.9
    adam_beta2: 0.999
    clip_gradient_norm: 1000
  scheduler:
    type: 'step'
    step: 100000
    gamma: 0.5
    
discriminator:
  type: ppde
  run_always: false
  config:
    norm: group
    num_layers: 4
    max_dim: 256
  optimizer:
    type: adam
    learning_rate: 0.0001 
    adam_beta: 0.9
    adam_beta2: 0.999
    clip_gradient_norm: 1000
  scheduler:
    type: 'step'
    step: 1000000
    gamma: 0.5
    
objectives:
  gan: ls
  perceptual:
    type: 'lpips_vgg'
    weight: 5
  reg:
    weight: 0.03
...